generals:
  # 0 - Don't save log
  # 1 - Save log
  save_log_file: 1
  refresh_page_shortcut: 1

hero:
  work_mod: "green"


screen:
  number_login_attempts: 3
  refresh_hunt: 7
  refresh_heroes: 25
  refresh_login: 0
  scroll_how_mutch_try_move_down: 4
  print_full_screen: true


threshold:
    default: 0.7
    hero_to_work: 0.9


telegram:
  token: ""
  chat_id: 0
  refresh_print_chest: 60
  